const yOpts=(a,w)=>{let r=[a,...w].map(String).filter((x,i,z)=>z.indexOf(x)===i);for(const f of ['Doğru bilgi edinirim.','Saygılı davranırım.','Korunmasına katkı sağlarım.','Bir yetişkinden yardım isterim.'])if(r.length<4&&!r.includes(f))r.push(f);return r.slice(0,4)},yQ=(p,v,a,w)=>[p,v,a,yOpts(a,w)];
const places=[['Kale','Tarihî mekân'],['Müze','Tarihî mekân'],['Eski köprü','Tarihî mekân'],['Ören yeri','Tarihî mekân'],['Tarihî cami','Tarihî mekân'],['Tarihî ev','Tarihî mekân'],['Anıt','Tarihî mekân'],['Kervansaray','Tarihî mekân'],['Antik tiyatro','Tarihî mekân'],['Tarihî saat kulesi','Tarihî mekân'],['Şelale','Doğal güzellik'],['Orman','Doğal güzellik'],['Göl','Doğal güzellik'],['Mağara','Doğal güzellik'],['Kanyon','Doğal güzellik'],['Dağ','Doğal güzellik'],['Plaj','Doğal güzellik'],['Yayla','Doğal güzellik'],['Vadi','Doğal güzellik'],['Nehir','Doğal güzellik'],['Traverten','Doğal güzellik'],['Milli park','Doğal güzellik'],['Tarihî çeşme','Tarihî mekân'],['Saray','Tarihî mekân'],['Doğal gölet','Doğal güzellik']];
const heritage=Array.from({length:100},(_,i)=>{let z=places[i%25],k=Math.floor(i/25);if(k===0)return yQ(z[0]+' hangi grupta değerlendirilir?','🏛️🌿 Tarih ve doğa',z[1],['Tarihî mekân','Doğal güzellik','Yönetim birimi']);if(k===1)return yQ(z[0]+' ziyaret edilirken en doğru davranış hangisidir?','🛡️ Değerlerimizi koruyalım','Çevreyi temiz tutup kurallara uymak',['Duvarlara yazı yazmak','Çöp bırakmak','Bitkilere ve eserlere zarar vermek']);if(k===2)return yQ(z[0]+' hakkında araştırma yaparken hangi bilgi önemlidir?','🔍 Yakın çevre araştırması','Yerin özelliği, önemi ve korunma biçimi',['Yalnız girişteki renk','Ziyaretçilerin kıyafetleri','Konuyla ilgisiz söylentiler']);return yQ(z[0]+' gelecek kuşaklara aktarılmak için nasıl korunmalıdır?','🌍 Ortak miras','Zarar vermeden kullanılıp yetkililere destek olunmalıdır.',['Parçaları hatıra olarak alınmalıdır.','Çevresi kirletilmelidir.','Koruma uyarıları yok sayılmalıdır.'])});
const units=[['Mahalle','Muhtar'],['Köy','Muhtar'],['İlçe','Kaymakam'],['İl','Vali'],['Belediye hizmetleri','Belediye başkanı'],['Mahalle sorunları','Muhtar'],['İlçedeki devlet işleri','Kaymakam'],['İldeki devlet işleri','Vali'],['Park ve temizlik hizmetleri','Belediye'],['Çöp toplama','Belediye'],['Yerel ulaşım','Belediye'],['Mahalle duyuruları','Muhtar'],['İlçe yönetimi','Kaymakamlık'],['İl yönetimi','Valilik'],['Yerel ortak ihtiyaçlar','Belediye'],['Köyün ortak işleri','Muhtar'],['İlçedeki resmî çalışmalar','Kaymakam'],['İldeki güvenlik ve koordinasyon','Vali'],['Çevre düzenleme','Belediye'],['Mahallede ikamet belgesi','Muhtarlık'],['İlçe merkezi','Kaymakamlık'],['İl merkezi','Valilik'],['Yerel yönetim','Belediye'],['Mahalle yönetimi','Muhtarlık'],['Kamu hizmetlerinin ilde yürütülmesi','Valilik']];
const management=Array.from({length:100},(_,i)=>{let z=units[i%25],k=Math.floor(i/25);if(k===0)return yQ(z[0]+' ile ilgili yönetici veya birim hangisidir?','🏢 Yönetim birimleri',z[1],['Muhtar','Kaymakam','Vali','Belediye'].filter(x=>x!==z[1]));if(k===1)return yQ(z[0]+' konusunda bilgi almak için hangi kuruma başvurmak uygundur?','📍 Yaşadığım yer',z[1].replace(' başkanı','').replace('Vali','Valilik').replace('Kaymakam','Kaymakamlık').replace('Muhtar','Muhtarlık'),['Muhtarlık','Kaymakamlık','Valilik','Belediye']);if(k===2)return yQ(z[0]+' hizmetinin amacı nedir?','🤝 Topluma hizmet','İnsanların ortak ihtiyaçlarını düzenli biçimde karşılamak',['Yalnız bir kişiye ayrıcalık sağlamak','Kuralları kaldırmak','Hizmetleri durdurmak']);return yQ(z[0]+' hakkında bir sorun fark edildiğinde ne yapılmalıdır?','🗣️ Katılım','Uygun yönetim birimine saygılı biçimde bildirilmelidir.',['Sorun büyütülmelidir.','Kamu malına zarar verilmelidir.','Yanlış bilgi yayılmalıdır.'])});
const ataturkFacts=[['Mustafa Kemal’in doğduğu şehir','Selanik'],['İlk başladığı geleneksel okul','Mahalle Mektebi'],['Daha sonra devam ettiği yenilikçi okul','Şemsi Efendi Mektebi'],['Askerî ortaokulu','Selanik Askerî Rüştiyesi'],['Lise öğrenimini sürdürdüğü okul','Manastır Askerî İdadisi'],['İstanbul’da devam ettiği askerî okul','Harp Okulu'],['Kurmay subay olarak mezun olduğu okul','Harp Akademisi'],['Matematik öğretmeninin verdiği ad','Kemal'],['Öğrencilikte sevdiği alanlardan biri','Matematik'],['Okumaya verdiği önem','Kitaplardan yeni bilgiler öğrenmek'],['Okul yaşamında öne çıkan özelliği','Çalışkanlık'],['Arkadaşlarıyla ilişkilerinde öne çıkan yönü','Düşüncelerini paylaşmak'],['Askerî okulu seçme isteği','Asker olma hedefi'],['Başarıya ulaşmasında etkili alışkanlık','Düzenli çalışmak'],['Farklı derslere ilgi göstermesi','Çok yönlü gelişmek'],['Tarih okumalarının katkısı','Vatan sevgisini güçlendirmek'],['Öğrencilik yıllarından çıkarılacak ders','Azimle çalışmak'],['Sorular sorması ve araştırması','Meraklı olmak'],['Kitap okuma alışkanlığı','Bilgi birikimini artırmak'],['Zorluklar karşısındaki tutumu','Kararlı olmak'],['Okuldaki görevlerini yapması','Sorumluluk sahibi olmak'],['Matematik dersindeki başarısı','Kemal adını almasında etkili olmak'],['Eğitim hayatındaki okul değişiklikleri','Hedeflerine göre öğrenimini sürdürmek'],['Öğrenmeye devam etmesi','Kendini geliştirmek'],['Öğrencilik yaşamının bize gösterdiği değer','Çalışma ve öğrenme sevgisi']];
const ataturk=Array.from({length:100},(_,i)=>{let z=ataturkFacts[i%25],k=Math.floor(i/25);if(k===0)return yQ('Atatürk’ün öğrencilik yıllarıyla ilgili “'+z[0]+'” bilgisi hangisidir?','📚 Atatürk öğrenciyken',z[1],[ataturkFacts[(i+4)%25][1],ataturkFacts[(i+9)%25][1],ataturkFacts[(i+14)%25][1]]);if(k===1)return yQ('“'+z[1]+'” bilgisi Atatürk’ün öğrencilik yaşamında neyle ilişkilidir?','🎓 Öğrenme yolculuğu',z[0],[ataturkFacts[(i+3)%25][0],ataturkFacts[(i+8)%25][0],ataturkFacts[(i+13)%25][0]]);if(k===2)return yQ('Atatürk’ün öğrencilik yıllarındaki “'+z[1]+'” örneğinden hangi sonuç çıkarılabilir?','🌟 Örnek öğrenci','Eğitime ve kendini geliştirmeye önem vermiştir.',['Çalışmayı gereksiz görmüştür.','Okumaktan kaçınmıştır.','Hedef belirlememiştir.']);return yQ('Atatürk’ün öğrencilik yaşamından yararlanarak “'+z[0]+'” konusunda hangi davranış örnek alınabilir?','✅ Geçmişten öğreniyorum','Merak etmek, araştırmak ve düzenli çalışmak',['Sorumlulukları ertelemek','Zorlukta hemen vazgeçmek','Dersleri önemsememek'])});
const national=[['23 Nisan','Ulusal Egemenlik ve Çocuk Bayramı'],['19 Mayıs','Atatürk’ü Anma, Gençlik ve Spor Bayramı'],['30 Ağustos','Zafer Bayramı'],['29 Ekim','Cumhuriyet Bayramı']];
const nationalPool=Array.from({length:100},(_,i)=>{let z=national[i%4],k=Math.floor(i/25)%4,activity=['Bayrak asmak','Törene katılmak','Şiir okumak','Bayramın anlamını öğrenmek','Saygı duruşuna katılmak','Millî birlik duygusunu paylaşmak','Okulu süslemek','Marşları saygıyla dinlemek','Atatürk’ü anmak','Geçmişteki mücadeleyi öğrenmek','Arkadaşlarla kutlama yapmak','Bayram panosu hazırlamak','Büyükleri dinlemek','Doğru tarih bilgisi öğrenmek','Bayrağa saygı göstermek','Tören kurallarına uymak','Bayramla ilgili kitap okumak','Sınıfta görev almak','Birlikte şarkı söylemek','Kutlamaya özen göstermek','Bayram mesajı hazırlamak','Millî değerleri korumak','Coşkuyu paylaşmak','Kutlamada çevreyi temiz tutmak','Bayramın kazanımlarını düşünmek'][i%25];if(k===0)return yQ(z[0]+' tarihinde hangi millî bayram kutlanır?','🇹🇷 Millî bayram',z[1],national.filter(x=>x[1]!==z[1]).map(x=>x[1]));if(k===1)return yQ(z[1]+' hangi tarihte kutlanır?','📅 Bayram takvimi',z[0],national.filter(x=>x[0]!==z[0]).map(x=>x[0]));if(k===2)return yQ(z[1]+' kutlanırken “'+activity+'” davranışı neyi destekler?','🎉 Bayram coşkusu','Millî birlik ve ortak değerleri',['Bayramı önemsememeyi','Kurallara uymamayı','Çevreye zarar vermeyi']);return yQ(z[1]+' neden önemlidir?','🌟 Millî değerler','Geçmişimizi, bağımsızlığımızı ve ortak değerlerimizi hatırlatır.',['Yalnızca tatil olduğu için','Ders araçlarını unutturmak için','Toplumsal bağları zayıflatmak için'])});
const religiousActs=['Büyükleri ziyaret etmek','Küçükleri sevindirmek','Bayramlaşmak','Küsleri barıştırmak','İhtiyaç sahiplerine yardım etmek','Misafire ikramda bulunmak','Temiz ve özenli giyinmek','Akrabaları aramak','Komşuları ziyaret etmek','Paylaşmak','Nazik konuşmak','Bayram sabahı aileyle buluşmak','Çocuklara sevgi göstermek','Yaşlıların hâlini sormak','Çevreyi temiz tutmak','İsraftan kaçınmak','Birlikte yemek yemek','Hediyeleşmek','Dayanışmak','Teşekkür etmek','Hoşgörülü olmak','Aile bağlarını güçlendirmek','Gelenekleri öğrenmek','Yardımlaşmak','Bayram sevincini paylaşmak'];
const religious=Array.from({length:100},(_,i)=>{let a=religiousActs[i%25],k=Math.floor(i/25),bayram=i%2?'Ramazan Bayramı':'Kurban Bayramı';if(k===0)return yQ(bayram+' sırasında “'+a+'” hangi değeri güçlendirir?','🌙 Dinî bayramlar','Sevgi, paylaşma ve dayanışmayı',['Bencilliği','Kabalığı','İletişimsizliği']);if(k===1)return yQ(bayram+' kutlanırken “'+a+'” nasıl yapılmalıdır?','🤝 Bayramlaşma','Saygılı, ölçülü ve içten biçimde',['Başkalarını rahatsız ederek','İsraf ederek','Kuralları önemsemeden']);if(k===2)return yQ('“'+a+'” dinî bayramların hangi toplumsal yönünü gösterir?','🏡 Birlikte kutluyoruz','İnsanları yakınlaştırmasını ve yardımlaşmayı artırmasını',['İnsanları birbirinden uzaklaştırmasını','Sorumlulukları kaldırmasını','Yalnız kalmayı artırmasını']);return yQ(bayram+' ile ilgili doğru davranış hangisidir?','🎊 Bayram değerleri',a,['Başkalarıyla alay etmek','Çevreyi kirletmek','İhtiyaç sahiplerini görmezden gelmek'])});
const sections=[
{code:'HB.2.4.1',color:'#168a77',soft:'#e3f8f2',icon:'🏛️',title:'Tarihî Mekân ve Doğal Güzelliklerimiz',intro:'Yakın çevredeki tarihî ve doğal değerleri tanı ve koru.',badge:'Kültür ve Doğa Rozeti',games:[{id:'miras100',icon:'🏞️',title:'Miras ve Doğa Kâşifi',desc:'100 farklı mekân ve koruma görevini tamamla.',q:heritage}]},
{code:'HB.2.4.2',color:'#3478c5',soft:'#e8f2ff',icon:'🏢',title:'Yönetim Birimlerini Tanıyalım',intro:'Mahalle, köy, ilçe, il ve belediye hizmetlerini yöneticileriyle ilişkilendir.',badge:'Yönetim Kâşifi Rozeti',games:[{id:'yonetim100',icon:'📍',title:'Yönetim Haritası',desc:'100 farklı yönetim ve hizmet sorusunu çöz.',q:management}]},
{code:'HB.2.4.3',color:'#d38b2d',soft:'#fff4df',icon:'📚',title:'Atatürk Öğrenciyken',intro:'Atatürk’ün öğrencilik yıllarını, okullarını ve örnek özelliklerini tanı.',badge:'Öğrenme Azmi Rozeti',games:[{id:'ataturk100',icon:'🎓',title:'Atatürk’ün Eğitim Yolculuğu',desc:'100 tarih ve değer sorusunu tamamla.',q:ataturk}]},
{code:'HB.2.4.4',color:'#d9415d',soft:'#ffe9ee',icon:'🇹🇷',title:'Millî Bayramlarımız',intro:'Millî bayramların tarihlerini, anlamlarını ve kutlama biçimlerini öğren.',badge:'Millî Değerler Rozeti',games:[{id:'milli100',icon:'🎉',title:'Bayram Takvimi',desc:'100 millî bayram görevini tamamla.',q:nationalPool}]},
{code:'HB.2.4.5',color:'#8157bd',soft:'#f2ebff',icon:'🌙',title:'Dinî Bayramlarımız',intro:'Dinî bayramlarda sevgi, saygı, paylaşma ve dayanışma davranışlarını uygula.',badge:'Bayramlaşma Rozeti',games:[{id:'dini100',icon:'🤝',title:'Bayramlaşma Bahçesi',desc:'100 bayram değeri sorusunu çöz.',q:religious}]}
];
let state=JSON.parse(localStorage.getItem("yer-ulke-progress")||'{"score":0,"wins":{}}');
const worlds=document.getElementById("worlds"),modal=document.getElementById("modal");
let game=null,qi=0,correct=0,locked=false;

function render(){
 worlds.innerHTML=sections.map((s,si)=>`<article class="world" style="--c:${s.color};--soft:${s.soft}">
 <div class="world-head"><div class="world-icon">${s.icon}</div><div><div class="code">${s.code}</div><h2>${si+1}. Bölüm · ${s.title}</h2><div>${s.badge} ${sectionWon(s)?"✅":"🔒"}</div></div></div>
 <div class="intro"><b>Konuyu keşfet</b>${s.intro}</div>
 <div class="cards">${s.games.map(g=>`<button class="card" data-id="${g.id}" style="--c:${s.color}"><span class="emoji">${g.icon}</span><h3>${g.title}</h3><p>${g.desc}</p><strong>${state.wins[g.id]?"Tamamlandı ✓":"Oyunu aç →"}</strong></button>`).join("")}</div></article>`).join("");
 document.querySelectorAll(".card").forEach(b=>b.onclick=()=>start(findGame(b.dataset.id)));
 updateProgress();
}
function findGame(id){for(const s of sections){const g=s.games.find(x=>x.id===id);if(g)return {...g,section:s}}}
function sectionWon(s){return s.games.every(g=>state.wins[g.id])}
function updateProgress(){document.getElementById("stars").textContent=state.score;document.getElementById("badges").textContent=sections.filter(sectionWon).length+"/5"}
function start(g){game={...g,q:[...g.q].sort(()=>Math.random()-.5)};qi=0;correct=0;locked=false;modal.hidden=false;document.body.style.overflow="hidden";showQ()}
function showQ(){
 const q=game.q[qi];locked=false;
 document.getElementById("gameHead").innerHTML=`<div class="game-title">${game.icon} ${game.title}</div><div class="game-meta">${game.section.code} · ${correct*10} puan</div>`;
 document.getElementById("bar").style.width=(qi/game.q.length*100)+"%";
 document.getElementById("question").innerHTML=`<div class="qno">GÖREV ${qi+1} / ${game.q.length}</div><div class="prompt">${q[0]}</div><div class="scene">${q[1]}</div>`;
 const opts=[...q[3]].sort(()=>Math.random()-.5);
 document.getElementById("answers").innerHTML=opts.map(a=>`<button class="answer">${a}</button>`).join("");
 document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;
 document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q[2]));
}
function answer(btn,right){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.textContent===String(right))b.classList.add("good")});if(btn.textContent===String(right)){correct++;btn.classList.add("good");document.getElementById("feedback").textContent="Harika! Doğru cevap. +10 puan ⭐"}else{btn.classList.add("bad");document.getElementById("feedback").textContent="Birlikte öğrendik! Doğru cevap: "+right}document.getElementById("next").hidden=false}
document.getElementById("next").onclick=()=>{qi++;if(qi<game.q.length)showQ();else finish()};
function finish(){const won=correct>=80;if(won&&!state.wins[game.id]){state.wins[game.id]=true;state.score+=correct*10}else if(!state.wins[game.id])state.score+=correct*10;localStorage.setItem("yer-ulke-progress",JSON.stringify(state));document.getElementById("bar").style.width="100%";document.getElementById("question").innerHTML=`<div class="result"><div class="cup">${won?"🏆":"🌱"}</div><h2>${won?"Görev tamamlandı!":"Bir kez daha deneyelim!"}</h2><p>100 sorudan ${correct} tanesini doğru cevapladın. ${won?"Bu oyunun yıldızını kazandın!":"80 doğruya ulaştığında oyunu tamamlayacaksın."}</p><button class="play-again" id="again">${won?"Oyunlara dön":"Yeniden oyna"}</button></div>`;document.getElementById("answers").innerHTML="";document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;document.getElementById("again").onclick=()=>won?closeGame():start(game);render()}
function closeGame(){modal.hidden=true;document.body.style.overflow="";render()}
document.getElementById("close").onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};
document.getElementById("reset").onclick=()=>{if(confirm("Tüm puan ve rozetler sıfırlansın mı?")){state={score:0,wins:{}};localStorage.setItem("yer-ulke-progress",JSON.stringify(state));render()}};
render();